// ═══════════════════════════════════════════════════════════
//  COSMIC ROLL — rarities.js
//  500 unique rarities, tiered by weight
// ═══════════════════════════════════════════════════════════

const TIERS = {
  COMMON:       { name:'Common',       color:'#a0a8b8', glow:'#a0a8b844', weight:5000 },
  UNCOMMON:     { name:'Uncommon',     color:'#4ade80', glow:'#4ade8044', weight:2500 },
  RARE:         { name:'Rare',         color:'#60a5fa', glow:'#60a5fa44', weight:1000 },
  EPIC:         { name:'Epic',         color:'#c084fc', glow:'#c084fc44', weight:400  },
  LEGENDARY:    { name:'Legendary',    color:'#f59e0b', glow:'#f59e0b44', weight:100  },
  MYTHIC:       { name:'Mythic',       color:'#f43f5e', glow:'#f43f5e44', weight:30   },
  DIVINE:       { name:'Divine',       color:'#e0f2fe', glow:'#e0f2fe66', weight:8    },
  COSMIC:       { name:'Cosmic',       color:'#7c3aed', glow:'#7c3aed88', weight:2    },
  TRANSCENDENT: { name:'Transcendent', color:'#ffffff', glow:'#ffffff99', weight:0.5  },
  VOID:         { name:'Void',         color:'#000000', glow:'#ff00ff88', weight:0.1  },
};

// Particle effect presets
const FX = {
  sparkle:    { particles:20,  speed:3,  spread:120, shape:'star',    colors:['#fff','#ffd700'] },
  burst:      { particles:40,  speed:6,  spread:360, shape:'circle',  colors:['#f59e0b','#ef4444','#fff'] },
  shatter:    { particles:60,  speed:8,  spread:360, shape:'shard',   colors:['#60a5fa','#93c5fd','#fff'] },
  nova:       { particles:80,  speed:10, spread:360, shape:'ring',    colors:['#c084fc','#e879f9','#fff'] },
  eclipse:    { particles:100, speed:12, spread:360, shape:'comet',   colors:['#f43f5e','#fb7185','#fde68a'] },
  ascend:     { particles:120, speed:14, spread:360, shape:'feather', colors:['#e0f2fe','#bae6fd','#7dd3fc'] },
  cosmos:     { particles:150, speed:16, spread:360, shape:'nebula',  colors:['#7c3aed','#a78bfa','#c4b5fd','#fff'] },
  transcend:  { particles:200, speed:20, spread:360, shape:'pulse',   colors:['#fff','#f0f','#0ff','#ff0'] },
  void_rift:  { particles:300, speed:25, spread:360, shape:'void',    colors:['#000','#ff00ff','#00ffff','#fff'] },
};

// Screen shake levels
const SHAKE = { none:0, small:3, medium:6, large:12, massive:20, apocalyptic:35 };

// Build all 500 rarities
// Format: { id, name, tier, desc, icon, fx, shake, cutscene(bool), bgColor, special }
const RARITIES = [

// ─────────────────────────── COMMON (1–100) ───────────────────────────
{ id:1,   tier:'COMMON', name:'Pebble',            icon:'🪨', desc:'Just a rock. A very ordinary rock.',                   fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:2,   tier:'COMMON', name:'Dandelion',          icon:'🌼', desc:'Yellow and fleeting.',                                 fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:3,   tier:'COMMON', name:'Rusty Coin',         icon:'🪙', desc:'Heads or tails? Neither, it\'s too corroded.',         fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:4,   tier:'COMMON', name:'Old Sock',           icon:'🧦', desc:'Where did the other one go?',                          fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:5,   tier:'COMMON', name:'Bread Crumb',        icon:'🍞', desc:'A crumb of potential.',                                fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:6,   tier:'COMMON', name:'Bent Paperclip',     icon:'📎', desc:'It used to hold things together.',                     fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:7,   tier:'COMMON', name:'Dry Leaf',           icon:'🍂', desc:'Autumn in your hand.',                                 fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:8,   tier:'COMMON', name:'Chewed Pencil',      icon:'✏️', desc:'Someone was nervous.',                                 fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:9,   tier:'COMMON', name:'Empty Cup',          icon:'🥤', desc:'The void stares back.',                                fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:10,  tier:'COMMON', name:'Forgotten Password', icon:'🔑', desc:'Was it capital P? Numbers? Ugh.',                      fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:11,  tier:'COMMON', name:'Wilted Rose',        icon:'🥀', desc:'Beauty in decay.',                                     fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:12,  tier:'COMMON', name:'Flat Tire',          icon:'🛞', desc:'Not the best day for a drive.',                        fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:13,  tier:'COMMON', name:'Spilled Milk',       icon:'🥛', desc:'No use crying.',                                       fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:14,  tier:'COMMON', name:'Tangled Earphones',  icon:'🎧', desc:'The eternal struggle.',                                fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:15,  tier:'COMMON', name:'Dead Plant',         icon:'🪴', desc:'You tried. Briefly.',                                  fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:16,  tier:'COMMON', name:'Empty Battery',      icon:'🔋', desc:'0%. No backup.',                                       fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:17,  tier:'COMMON', name:'Expired Coupon',     icon:'🏷️', desc:'15% off, last month.',                                 fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:18,  tier:'COMMON', name:'Burnt Toast',        icon:'🍞', desc:'Breakfast ruined, morning ruined.',                    fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:19,  tier:'COMMON', name:'Blurry Photo',       icon:'📷', desc:'Was that a cat? A ghost?',                             fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:20,  tier:'COMMON', name:'Broken Umbrella',    icon:'☂️', desc:'Irony: it rains.',                                     fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:21,  tier:'COMMON', name:'Lint Ball',          icon:'🫧', desc:'Pocket treasure.',                                     fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:22,  tier:'COMMON', name:'Melted Ice Cream',   icon:'🍦', desc:'You were too slow.',                                   fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:23,  tier:'COMMON', name:'Missed Call',        icon:'📵', desc:'Who was that? You\'ll never know.',                    fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:24,  tier:'COMMON', name:'Cloudy Day',         icon:'☁️', desc:'The sun is somewhere, probably.',                      fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:25,  tier:'COMMON', name:'Parking Ticket',     icon:'🎫', desc:'$45 of regret.',                                       fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:26,  tier:'COMMON', name:'Static Noise',       icon:'📻', desc:'Nothing on the radio.',                                fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:27,  tier:'COMMON', name:'Squeaky Shoe',       icon:'👟', desc:'Everyone hears you coming.',                           fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:28,  tier:'COMMON', name:'Stale Chip',         icon:'🍟', desc:'The tragedy of the last chip.',                        fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:29,  tier:'COMMON', name:'Monday Morning',     icon:'😴', desc:'Enough said.',                                         fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:30,  tier:'COMMON', name:'Low WiFi Signal',    icon:'📶', desc:'Buffering... buffering... buffering...',                fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:31,  tier:'COMMON', name:'Dropped Fork',       icon:'🍴', desc:'The universe says sit down.',                          fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:32,  tier:'COMMON', name:'Wrong Direction',    icon:'🗺️', desc:'You\'re 3 miles off.',                                 fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:33,  tier:'COMMON', name:'Out of Ink',         icon:'🖊️', desc:'Critical pen failure.',                                fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:34,  tier:'COMMON', name:'Squeaky Door',       icon:'🚪', desc:'Hinges haven\'t met oil in years.',                    fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:35,  tier:'COMMON', name:'Scuffed Sneaker',    icon:'👠', desc:'Still wearable. Barely.',                              fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:36,  tier:'COMMON', name:'Forgotten Dream',    icon:'💭', desc:'It was important. You felt it. Gone.',                 fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:37,  tier:'COMMON', name:'Bus Missed',         icon:'🚌', desc:'Next one\'s in 40 minutes.',                           fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:38,  tier:'COMMON', name:'Broken Shoelace',    icon:'🪢', desc:'Always at the worst time.',                            fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:39,  tier:'COMMON', name:'Dull Pencil',        icon:'✏️', desc:'The lines are wide. Ideas are narrow.',                fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:40,  tier:'COMMON', name:'Warm Soda',          icon:'🥫', desc:'Room temperature disappointment.',                     fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:41,  tier:'COMMON', name:'Itchy Tag',          icon:'🏷️', desc:'Cut it off. Freedom.',                                 fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:42,  tier:'COMMON', name:'Spiderweb Corner',   icon:'🕸️', desc:'The spider is watching.',                              fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:43,  tier:'COMMON', name:'Foggy Mirror',       icon:'🪞', desc:'Who is that? A ghost? You.',                           fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:44,  tier:'COMMON', name:'Old Receipt',        icon:'🧾', desc:'$3.49 for chips, years ago.',                          fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:45,  tier:'COMMON', name:'Faded Sticker',      icon:'⭐', desc:'It was a star, once.',                                 fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:46,  tier:'COMMON', name:'Missed High Five',   icon:'✋', desc:'The cringe echoes.',                                   fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:47,  tier:'COMMON', name:'Sour Candy',         icon:'🍬', desc:'Pucker up.',                                           fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:48,  tier:'COMMON', name:'Nearly Empty Tube',  icon:'🪥', desc:'Just a little left. Just a little.',                   fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:49,  tier:'COMMON', name:'Cold Coffee',        icon:'☕', desc:'It was hot. Once.',                                    fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:50,  tier:'COMMON', name:'Static Hair',        icon:'💇', desc:'The balloon is nearby.',                               fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:51,  tier:'COMMON', name:'Gravel',             icon:'⚫', desc:'Just normal gravel.',                                  fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:52,  tier:'COMMON', name:'Fog',                icon:'🌫️', desc:'Everything is unclear.',                               fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:53,  tier:'COMMON', name:'Mud Puddle',         icon:'💧', desc:'Right on your shoes.',                                 fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:54,  tier:'COMMON', name:'Faint Echo',         icon:'🔊', desc:'Hello? ...hello? ...hello?',                           fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:55,  tier:'COMMON', name:'Torn Paper',         icon:'📄', desc:'The idea was almost captured.',                        fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:56,  tier:'COMMON', name:'Dim Bulb',           icon:'💡', desc:'Not quite bright enough.',                             fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:57,  tier:'COMMON', name:'Crumpled Can',       icon:'🥫', desc:'Post-drink sadness.',                                  fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:58,  tier:'COMMON', name:'Wobbly Table',       icon:'🪑', desc:'Put a napkin under the leg.',                          fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:59,  tier:'COMMON', name:'Loose Button',       icon:'🔘', desc:'One more wash and it\'s gone.',                        fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:60,  tier:'COMMON', name:'Dusty Shelf',        icon:'📚', desc:'Last cleaned: never.',                                 fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:61,  tier:'COMMON', name:'Small Breeze',       icon:'🌬️', desc:'Barely noticeable.',                                   fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:62,  tier:'COMMON', name:'Chipped Mug',        icon:'☕', desc:'Handle with care. Or don\'t.',                         fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:63,  tier:'COMMON', name:'Soggy Cardboard',    icon:'📦', desc:'No longer a box.',                                     fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:64,  tier:'COMMON', name:'Unread Email',       icon:'📧', desc:'Subject: Re: Re: Re: Re:',                             fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:65,  tier:'COMMON', name:'Slow Internet',      icon:'🐌', desc:'Loading... please wait.',                              fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:66,  tier:'COMMON', name:'Paper Cut',          icon:'🩹', desc:'The betrayal of office supplies.',                     fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:67,  tier:'COMMON', name:'Wrong Order',        icon:'🍔', desc:'They put onions on it.',                               fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:68,  tier:'COMMON', name:'Hiccup',             icon:'😮', desc:'Three seconds of pure chaos.',                         fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:69,  tier:'COMMON', name:'Misplaced Keys',     icon:'🗝️', desc:'They were in your pocket.',                            fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:70,  tier:'COMMON', name:'Drizzle',            icon:'🌧️', desc:'Not enough for an umbrella, too much for comfort.',    fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:71,  tier:'COMMON', name:'Cracked Screen',     icon:'📱', desc:'The spider web spreads.',                              fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:72,  tier:'COMMON', name:'Junk Mail',          icon:'📬', desc:'Congratulations! You won nothing.',                    fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:73,  tier:'COMMON', name:'Stuck Zipper',       icon:'🧥', desc:'Wedged. Unbudging. Forever.',                          fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:74,  tier:'COMMON', name:'Lukewarm Shower',    icon:'🚿', desc:'Not hot. Not cold. Nothing.',                          fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:75,  tier:'COMMON', name:'Lint Roller',        icon:'🧹', desc:'Battle against the fuzz.',                             fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:76,  tier:'COMMON', name:'Overcast Sky',       icon:'🌥️', desc:'The sun gave up today.',                               fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:77,  tier:'COMMON', name:'Empty Wallet',       icon:'👛', desc:'The cards are all that remain.',                       fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:78,  tier:'COMMON', name:'Awkward Silence',    icon:'😶', desc:'Three... two... one...',                               fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:79,  tier:'COMMON', name:'Splinter',           icon:'🪵', desc:'Tiny. Painful. Personal.',                             fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:80,  tier:'COMMON', name:'Blur',               icon:'🌀', desc:'Everything is motion.',                                fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:81,  tier:'COMMON', name:'Forgotten Errand',   icon:'📋', desc:'What was it again?',                                   fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:82,  tier:'COMMON', name:'Thin Ice',           icon:'❄️', desc:'Proceed with caution.',                                fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:83,  tier:'COMMON', name:'Sticky Note',        icon:'📝', desc:'Important! (content unclear)',                         fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:84,  tier:'COMMON', name:'Odd Smell',          icon:'👃', desc:'What IS that?',                                        fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:85,  tier:'COMMON', name:'Smudge',             icon:'🌑', desc:'On the lens. On the soul.',                            fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:86,  tier:'COMMON', name:'Rain on Window',     icon:'🪟', desc:'The world, blurred.',                                  fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:87,  tier:'COMMON', name:'Yawn',               icon:'🥱', desc:'So contagious.',                                       fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:88,  tier:'COMMON', name:'Coin Flip Tails',    icon:'🌕', desc:'Not heads.',                                           fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:89,  tier:'COMMON', name:'Out-of-Tune Note',   icon:'🎵', desc:'E flat, when you wanted E.',                           fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:90,  tier:'COMMON', name:'Bent Straw',         icon:'🥤', desc:'Sip at an angle.',                                     fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:91,  tier:'COMMON', name:'Traffic Jam',        icon:'🚗', desc:'10 miles. 2 hours.',                                   fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:92,  tier:'COMMON', name:'Foggy Memory',       icon:'🧠', desc:'Almost recall it.',                                    fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:93,  tier:'COMMON', name:'Missed Alarm',       icon:'⏰', desc:'You were so sure you set it.',                         fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:94,  tier:'COMMON', name:'Unmatched Socks',    icon:'🧦', desc:'Bold fashion choice.',                                 fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:95,  tier:'COMMON', name:'Rainstorm Inbound',  icon:'⛈️', desc:'The clouds are planning something.',                   fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:96,  tier:'COMMON', name:'Crinkled Map',       icon:'🗺️', desc:'You can almost read it.',                              fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:97,  tier:'COMMON', name:'Broken Crayon',      icon:'🖍️', desc:'Snapped in half. Both halves still work.',             fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:98,  tier:'COMMON', name:'Empty Jar',          icon:'🫙', desc:'Used to be something good.',                           fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:99,  tier:'COMMON', name:'Tangled Necklace',   icon:'📿', desc:'An hour minimum to undo.',                             fx:'sparkle', shake:SHAKE.none,  cutscene:false },
{ id:100, tier:'COMMON', name:'Weak Handshake',     icon:'🤝', desc:'Limp. Forgettable. Gone.',                             fx:'sparkle', shake:SHAKE.none,  cutscene:false },

// ─────────────────────────── UNCOMMON (101–200) ───────────────────────────
{ id:101, tier:'UNCOMMON', name:'Copper Charm',       icon:'🔮', desc:'A little luck clings to it.',                           fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:102, tier:'UNCOMMON', name:'Glowing Mushroom',   icon:'🍄', desc:'Bioluminescent and slightly ominous.',                  fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:103, tier:'UNCOMMON', name:'Silver Feather',     icon:'🪶', desc:'Fell from something that flies higher.',                fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:104, tier:'UNCOMMON', name:'Lucky Clover',       icon:'🍀', desc:'Four leafed, fortune-kissed.',                          fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:105, tier:'UNCOMMON', name:'Moon Petal',         icon:'🌸', desc:'Blooms only in silver light.',                          fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:106, tier:'UNCOMMON', name:'Shiny Rock',         icon:'💎', desc:'Not a gem — just really shiny.',                        fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:107, tier:'UNCOMMON', name:'Bottled Wind',       icon:'💨', desc:'Captured from the top of a mountain.',                  fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:108, tier:'UNCOMMON', name:'Echo Stone',         icon:'🪨', desc:'Whisper to it. It remembers.',                          fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:109, tier:'UNCOMMON', name:'Midnight Ink',       icon:'🖊️', desc:'What you write with this, comes true.',                 fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:110, tier:'UNCOMMON', name:'Firefly Jar',        icon:'🫙', desc:'Tiny lights, dancing in glass.',                        fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:111, tier:'UNCOMMON', name:'Warm Crystal',       icon:'🔷', desc:'Pulses gently with inner heat.',                        fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:112, tier:'UNCOMMON', name:'Frozen Tear',        icon:'💧', desc:'Sorrow turned beautiful.',                              fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:113, tier:'UNCOMMON', name:'Fox Tail',           icon:'🦊', desc:'Left behind by a clever creature.',                     fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:114, tier:'UNCOMMON', name:'Dusk Compass',       icon:'🧭', desc:'Always points toward something interesting.',           fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:115, tier:'UNCOMMON', name:'Pearl Dust',         icon:'🌟', desc:'Ground from real ocean pearls.',                        fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:116, tier:'UNCOMMON', name:'Midnight Flower',    icon:'🌙', desc:'Only opens in darkness.',                               fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:117, tier:'UNCOMMON', name:'Storm Bottle',       icon:'⛈️', desc:'A miniature thunderstorm, contained.',                  fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:118, tier:'UNCOMMON', name:'Sunken Marble',      icon:'🔵', desc:'Deeper blue than any ocean.',                           fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:119, tier:'UNCOMMON', name:'Ghost Candle',       icon:'🕯️', desc:'Burns without flame.',                                  fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:120, tier:'UNCOMMON', name:'Crow Rune',          icon:'🪬', desc:'Marks you as someone worth watching.',                  fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:121, tier:'UNCOMMON', name:'Bronze Lantern',     icon:'🏮', desc:'Lights the dark, one step at a time.',                  fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:122, tier:'UNCOMMON', name:'Dreaming Seed',      icon:'🌱', desc:'Plant it under moonlight.',                             fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:123, tier:'UNCOMMON', name:'Mist Fragment',      icon:'🌫️', desc:'Solidified fog from a high mountain.',                  fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:124, tier:'UNCOMMON', name:'Iron Acorn',         icon:'🪙', desc:'Small, dense, impossibly heavy.',                       fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:125, tier:'UNCOMMON', name:'Thorn Crown',        icon:'👑', desc:'Painful to wear, but you will.',                        fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:126, tier:'UNCOMMON', name:'River Glass',        icon:'🫧', desc:'Smoothed by a thousand years of current.',              fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:127, tier:'UNCOMMON', name:'Smoke Bead',         icon:'⚫', desc:'Holds the scent of an ancient fire.',                   fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:128, tier:'UNCOMMON', name:'Hollow Arrow',       icon:'🏹', desc:'Points at what you\'re missing.',                       fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:129, tier:'UNCOMMON', name:'Bone Dice',          icon:'🎲', desc:'Carved from something that used to wander.',            fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:130, tier:'UNCOMMON', name:'Salt Circle',        icon:'⭕', desc:'Stand inside. Nothing bad enters.',                     fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:131, tier:'UNCOMMON', name:'Rain-Worn Stone',    icon:'🪨', desc:'Polished by countless storms.',                         fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:132, tier:'UNCOMMON', name:'Twisted Vine',       icon:'🌿', desc:'Spiraling with old magic.',                             fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:133, tier:'UNCOMMON', name:'Driftwood Sigil',    icon:'🪵', desc:'The sea carved it intentionally.',                      fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:134, tier:'UNCOMMON', name:'Sulfur Bead',        icon:'🟡', desc:'Smells of lightning and potential.',                    fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:135, tier:'UNCOMMON', name:'Moth Wing',          icon:'🦋', desc:'From a moth that flew too close to the sun.',           fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:136, tier:'UNCOMMON', name:'Cold Spark',         icon:'✨', desc:'A spark that doesn\'t burn.',                           fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:137, tier:'UNCOMMON', name:'Forest Echo',        icon:'🌲', desc:'The trees are still talking.',                          fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:138, tier:'UNCOMMON', name:'Wax Seal',           icon:'🔴', desc:'Marks a secret kept for centuries.',                    fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:139, tier:'UNCOMMON', name:'Phantom Bell',       icon:'🔔', desc:'Rings when you\'re not listening.',                     fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:140, tier:'UNCOMMON', name:'Obsidian Chip',      icon:'◼️', desc:'Volcanic glass that holds an edge forever.',            fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:141, tier:'UNCOMMON', name:'Wandering Cloud',    icon:'☁️', desc:'Follows you around. Mostly harmless.',                  fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:142, tier:'UNCOMMON', name:'Amber Drop',         icon:'🟠', desc:'Ancient resin, frozen in time.',                        fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:143, tier:'UNCOMMON', name:'Charcoal Sketch',    icon:'✏️', desc:'A face stares back. You don\'t recognize it.',          fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:144, tier:'UNCOMMON', name:'Deep Water Sound',   icon:'🌊', desc:'A recording of the deepest ocean.',                     fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:145, tier:'UNCOMMON', name:'Wolf Fang',          icon:'🐺', desc:'Fell out willingly.',                                   fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:146, tier:'UNCOMMON', name:'Copper Whistle',     icon:'🎺', desc:'Calls things that don\'t have names.',                  fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:147, tier:'UNCOMMON', name:'Tangled Roots',      icon:'🌱', desc:'The underground network of an old tree.',               fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:148, tier:'UNCOMMON', name:'Bat Wing Fragment',  icon:'🦇', desc:'Lightweight, durable, eerie.',                          fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:149, tier:'UNCOMMON', name:'Half a Map',         icon:'🗺️', desc:'The other half is out there.',                          fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:150, tier:'UNCOMMON', name:'Velvet Pouch',       icon:'👜', desc:'The contents shift when you\'re not looking.',          fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:151, tier:'UNCOMMON', name:'Comet Dust',         icon:'💫', desc:'Collected from a passing streak.',                      fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:152, tier:'UNCOMMON', name:'Green Flame',        icon:'🔥', desc:'Burns cold. Feels warm inside.',                        fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:153, tier:'UNCOMMON', name:'Raven Claw',         icon:'🦅', desc:'A gift from the sky watchers.',                         fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:154, tier:'UNCOMMON', name:'Sea Foam Vial',      icon:'🧪', desc:'Contains the laughter of waves.',                       fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:155, tier:'UNCOMMON', name:'Carved Acorn',       icon:'🌰', desc:'Etched with a language you almost understand.',         fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:156, tier:'UNCOMMON', name:'Hallow Bone',        icon:'🦴', desc:'Lighter than air. Tougher than iron.',                  fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:157, tier:'UNCOMMON', name:'Bitter Root',        icon:'🌿', desc:'The healers sought this.',                              fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:158, tier:'UNCOMMON', name:'Pale Coin',          icon:'🪙', desc:'From a kingdom no one remembers.',                      fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:159, tier:'UNCOMMON', name:'Sea Shell Spiral',   icon:'🐚', desc:'The ocean is still inside.',                            fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:160, tier:'UNCOMMON', name:'Frozen Flame',       icon:'🔵', desc:'Paradox, preserved.',                                   fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:161, tier:'UNCOMMON', name:'Stone Eye',          icon:'👁️', desc:'It blinks. You saw it blink.',                          fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:162, tier:'UNCOMMON', name:'Dark Honey',         icon:'🍯', desc:'From bees that only work at night.',                    fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:163, tier:'UNCOMMON', name:'Phantom Step',       icon:'👣', desc:'A footprint in solid stone.',                           fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:164, tier:'UNCOMMON', name:'Tide Rune',          icon:'🌀', desc:'Push it, the tide answers.',                            fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:165, tier:'UNCOMMON', name:'Ember Shard',        icon:'🔴', desc:'From the last fire of a dead volcano.',                 fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:166, tier:'UNCOMMON', name:'Bone Flute',         icon:'🎵', desc:'Plays a note that means goodbye.',                      fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:167, tier:'UNCOMMON', name:'Smoke Ring',         icon:'💍', desc:'Hardened smoke, worn as jewelry.',                      fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:168, tier:'UNCOMMON', name:'Mirror Shard',       icon:'🪞', desc:'Reflects a slightly different you.',                    fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:169, tier:'UNCOMMON', name:'Russet Claw',        icon:'🦀', desc:'From something that walked sideways through time.',     fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:170, tier:'UNCOMMON', name:'Drowned Lantern',    icon:'🏮', desc:'Still lit, somehow.',                                   fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:171, tier:'UNCOMMON', name:'Pressed Fern',       icon:'🌿', desc:'Kept between pages of an unknown book.',               fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:172, tier:'UNCOMMON', name:'Chalk Circle',       icon:'⭕', desc:'Step inside. Time slows.',                             fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:173, tier:'UNCOMMON', name:'Worn Compass',       icon:'🧭', desc:'North shifts, but it keeps trying.',                    fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:174, tier:'UNCOMMON', name:'Serpent Scale',      icon:'🐍', desc:'Shed willingly. Left as a marker.',                     fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:175, tier:'UNCOMMON', name:'Iridescent Beetle',  icon:'🪲', desc:'A living jewel that chose to stay.',                    fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:176, tier:'UNCOMMON', name:'Smoldering Coal',    icon:'⚫', desc:'Still warm from last week\'s fire.',                    fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:177, tier:'UNCOMMON', name:'Tide Glass',         icon:'🔵', desc:'Shaped by the pull of the moon.',                       fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:178, tier:'UNCOMMON', name:'Carved Knot',        icon:'🪢', desc:'The knot undoes itself at midnight.',                   fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:179, tier:'UNCOMMON', name:'Warm Quartz',        icon:'🔶', desc:'Body heat makes it glow softly.',                       fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:180, tier:'UNCOMMON', name:'Sky Root',           icon:'🌱', desc:'Grows upward into clouds.',                             fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:181, tier:'UNCOMMON', name:'Glass Moth',         icon:'🦋', desc:'Fragile, translucent, preserved.',                      fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:182, tier:'UNCOMMON', name:'Brine Seed',         icon:'🌊', desc:'Plant in saltwater. Grows metal.',                      fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:183, tier:'UNCOMMON', name:'Wren Whistle',       icon:'🐦', desc:'Calls birds that know secrets.',                        fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:184, tier:'UNCOMMON', name:'Pale Fossil',        icon:'🦴', desc:'Life from 300 million years ago.',                      fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:185, tier:'UNCOMMON', name:'Verdant Acorn',      icon:'🌰', desc:'Plant it and watch the forest begin.',                  fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:186, tier:'UNCOMMON', name:'Crescent Blade',     icon:'🌙', desc:'Only sharp on moonlit nights.',                         fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:187, tier:'UNCOMMON', name:'Clay Face',          icon:'🎭', desc:'Smiles when no one looks.',                             fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:188, tier:'UNCOMMON', name:'Iron Coral',         icon:'🪸', desc:'From a sea of molten rock.',                            fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:189, tier:'UNCOMMON', name:'Dried Storm',        icon:'⛈️', desc:'A pressed storm petal.',                                fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:190, tier:'UNCOMMON', name:'Hollow Moon Stone',  icon:'🌕', desc:'Empty inside. Hums.',                                   fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:191, tier:'UNCOMMON', name:'Owl Talon',          icon:'🦉', desc:'Wisdom made physical.',                                 fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:192, tier:'UNCOMMON', name:'Cave Glow',          icon:'🫧', desc:'Phosphorescent cave moss.',                             fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:193, tier:'UNCOMMON', name:'Iron Splinter',      icon:'🗡️', desc:'From a blade that broke on something harder.',          fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:194, tier:'UNCOMMON', name:'Frog Stone',         icon:'🐸', desc:'The rain likes to gather here.',                        fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:195, tier:'UNCOMMON', name:'Whispering Shell',   icon:'🐚', desc:'Press it to your ear. Don\'t.',                         fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:196, tier:'UNCOMMON', name:'Old Compass',        icon:'🧭', desc:'Points to something you\'ve been avoiding.',            fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:197, tier:'UNCOMMON', name:'Star Map Fragment',  icon:'🌌', desc:'Part of a larger, stranger picture.',                   fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:198, tier:'UNCOMMON', name:'Smoke Serpent',      icon:'🐉', desc:'A coil of smoke that holds its shape.',                 fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:199, tier:'UNCOMMON', name:'Glass Antler',       icon:'🦌', desc:'From a deer made entirely of light.',                   fx:'sparkle', shake:SHAKE.small,  cutscene:false },
{ id:200, tier:'UNCOMMON', name:'Living Shadow',      icon:'🌑', desc:'It moved on its own. You watched.',                     fx:'sparkle', shake:SHAKE.small,  cutscene:false },

// ─────────────────────────── RARE (201–300) ───────────────────────────
{ id:201, tier:'RARE', name:'Sapphire Shard',       icon:'💠', desc:'Broken from a gem the size of a house.',                 fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:202, tier:'RARE', name:'Storm Prism',          icon:'🔷', desc:'Refracts light into colors that don\'t exist.',          fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:203, tier:'RARE', name:'Rift Pearl',           icon:'🔘', desc:'Formed in the space between two worlds.',                fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:204, tier:'RARE', name:'Tidal Blade',          icon:'🗡️', desc:'Cuts like a wave, just as relentless.',                  fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:205, tier:'RARE', name:'Lunar Sigil',          icon:'🌙', desc:'Activated only by full moon.',                           fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:206, tier:'RARE', name:'Spectral Ring',        icon:'💍', desc:'Worn by someone you can\'t quite see.',                  fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:207, tier:'RARE', name:'Voidborn Seed',        icon:'🌑', desc:'Grows in total darkness. Toward the light.',             fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:208, tier:'RARE', name:'Crystalline Tear',     icon:'💎', desc:'From an entity that only weeps perfection.',             fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:209, tier:'RARE', name:'Abyssal Hook',         icon:'🪝', desc:'What it pulls up from the deep is always worth it.',     fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:210, tier:'RARE', name:'Celestial Compass',    icon:'🧭', desc:'Points to wherever you need to be.',                     fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:211, tier:'RARE', name:'Phantom Coin',         icon:'🪙', desc:'Both heads and tails. Simultaneously.',                  fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:212, tier:'RARE', name:'Frozen Thunder',       icon:'⚡', desc:'Lightning stopped mid-bolt.',                            fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:213, tier:'RARE', name:'Blood Orchid',         icon:'🌺', desc:'Drinks moonlight, not water.',                           fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:214, tier:'RARE', name:'Deep Eye',             icon:'👁️', desc:'Sees through walls, time, and excuses.',                 fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:215, tier:'RARE', name:'Sky Anchor',           icon:'⚓', desc:'Holds clouds in place. Somehow.',                        fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:216, tier:'RARE', name:'Void Marble',          icon:'🔮', desc:'Contains a pocket of nothing.',                          fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:217, tier:'RARE', name:'Aurora Thread',        icon:'🧵', desc:'Woven from northern lights.',                            fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:218, tier:'RARE', name:'Iron Constellation',   icon:'⭐', desc:'Stars forged into a shape.',                             fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:219, tier:'RARE', name:'Ember Crown',          icon:'👑', desc:'Burns without consuming.',                               fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:220, tier:'RARE', name:'Drowned Rune',         icon:'🪬', desc:'Carved by the current over millennia.',                  fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:221, tier:'RARE', name:'Luminous Root',        icon:'🌱', desc:'Grows light like a plant grows leaves.',                 fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:222, tier:'RARE', name:'Chrome Lotus',         icon:'🪷', desc:'Metal petals, velvet center.',                           fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:223, tier:'RARE', name:'Painted Storm',        icon:'🖼️', desc:'A storm captured on canvas that still moves.',           fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:224, tier:'RARE', name:'Deep Tide Key',        icon:'🗝️', desc:'Opens doors in places that have no doors.',              fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:225, tier:'RARE', name:'Neon Relic',           icon:'🔦', desc:'Ancient, but somehow electric.',                         fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:226, tier:'RARE', name:'Gravity Stone',        icon:'🟤', desc:'Things fall toward it slightly.',                        fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:227, tier:'RARE', name:'Forgotten Sun',        icon:'☀️', desc:'A sun that never came back.',                             fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:228, tier:'RARE', name:'Time Crack',           icon:'⏳', desc:'A hairline fracture in a moment.',                       fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:229, tier:'RARE', name:'Prism Heart',          icon:'❤️', desc:'Refracts emotion into color.',                            fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:230, tier:'RARE', name:'Hex Bead',             icon:'🔮', desc:'Six sides. Six outcomes. All yours.',                    fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:231, tier:'RARE', name:'Magma String',         icon:'🌋', desc:'Thread pulled from cooling lava.',                       fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:232, tier:'RARE', name:'Hollow Galaxy',        icon:'🌌', desc:'A galaxy the size of your palm.',                        fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:233, tier:'RARE', name:'Web of Fate',          icon:'🕸️', desc:'A spider web with meanings in every node.',              fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:234, tier:'RARE', name:'Blue Phoenix Egg',     icon:'🥚', desc:'Not hatched. Patient.',                                  fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:235, tier:'RARE', name:'Echo Prism',           icon:'🔷', desc:'Play a sound into it, get back the truth.',              fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:236, tier:'RARE', name:'Night Glass',          icon:'🌃', desc:'A window that only shows the night.',                    fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:237, tier:'RARE', name:'Runed Spine',          icon:'🦴', desc:'A vertebra carved with prophecy.',                       fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:238, tier:'RARE', name:'Astral Rope',          icon:'🪢', desc:'Ties together distant places.',                          fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:239, tier:'RARE', name:'Cloud Fragment',       icon:'☁️', desc:'Actual cloud, held solid.',                              fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:240, tier:'RARE', name:'Star Candle',          icon:'🕯️', desc:'Burns with the light of a distant star.',               fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:241, tier:'RARE', name:'Iron Feather',         icon:'🪶', desc:'Heavy as regret, light as hope.',                        fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:242, tier:'RARE', name:'Woven Light',          icon:'🌟', desc:'Light woven into a solid strand.',                       fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:243, tier:'RARE', name:'Submerged Crown',      icon:'👑', desc:'Rusted. Still royal.',                                   fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:244, tier:'RARE', name:'Volcanic Lens',        icon:'🔍', desc:'See through it: everything is red hot.',                 fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:245, tier:'RARE', name:'Bound Storm',          icon:'⛈️', desc:'Compressed into a silver sphere.',                       fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:246, tier:'RARE', name:'Phosphor Shell',       icon:'🐚', desc:'Glows in salt water.',                                   fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:247, tier:'RARE', name:'Tundra Rose',          icon:'🌹', desc:'Blooms at -40°. Never wilts.',                           fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:248, tier:'RARE', name:'Ancient Lever',        icon:'🔧', desc:'Moves something enormous, somewhere.',                   fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:249, tier:'RARE', name:'Echo Chime',           icon:'🎐', desc:'Rings with sounds of another era.',                      fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:250, tier:'RARE', name:'Shattered Mirror Orb', icon:'🔮', desc:'A sphere of broken reflections.',                        fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:251, tier:'RARE', name:'Thread of Dawn',       icon:'🌄', desc:'The first thread of morning light.',                     fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:252, tier:'RARE', name:'Sea Dragon Scale',     icon:'🐉', desc:'From a creature that sleeps under currents.',            fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:253, tier:'RARE', name:'Carved Moon',          icon:'🌙', desc:'Full, crescent, and new at once.',                       fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:254, tier:'RARE', name:'Bone Lantern',         icon:'🏮', desc:'The flame inside is blue. Always.',                      fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:255, tier:'RARE', name:'Crystal Serpent',      icon:'🐍', desc:'Moves slowly. Thinks fast.',                             fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:256, tier:'RARE', name:'Thought Fragment',     icon:'💭', desc:'A thought that got away. Yours.',                        fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:257, tier:'RARE', name:'Quantum Acorn',        icon:'🌰', desc:'Simultaneously planted and not.',                        fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:258, tier:'RARE', name:'Sapphire Wing',        icon:'🦋', desc:'From a butterfly that flies between moments.',           fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:259, tier:'RARE', name:'Glacier Spike',        icon:'🧊', desc:'From the tip of a 10,000-year-old glacier.',             fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:260, tier:'RARE', name:'Cosmic Thorn',         icon:'🌹', desc:'Grows at the edge of the universe.',                     fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:261, tier:'RARE', name:'Phase Stone',          icon:'💠', desc:'Flickers between solid and intangible.',                 fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:262, tier:'RARE', name:'Nebula Thread',        icon:'🌌', desc:'Pulled from a star nursery.',                            fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:263, tier:'RARE', name:'Temporal Lens',        icon:'🔭', desc:'See 5 minutes into the future. Nothing more.',          fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:264, tier:'RARE', name:'Moonmelt Blade',       icon:'🗡️', desc:'Forged from solidified moonlight.',                      fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:265, tier:'RARE', name:'Hive Crystal',         icon:'🐝', desc:'Thousands of chambers, each a tiny world.',              fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:266, tier:'RARE', name:'Amber Eye',            icon:'👁️', desc:'An eye preserved in amber. Still blinking.',             fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:267, tier:'RARE', name:'Rift Dust',            icon:'✨', desc:'From the tear between dimensions.',                      fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:268, tier:'RARE', name:'Celestine Fragment',   icon:'💎', desc:'A chip of the sky itself.',                              fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:269, tier:'RARE', name:'Crystallized Echo',    icon:'🔊', desc:'A sound frozen mid-vibration.',                          fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:270, tier:'RARE', name:'Night Compass',        icon:'🧭', desc:'Only works in darkness. Points inward.',                 fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:271, tier:'RARE', name:'Star Fragment',        icon:'⭐', desc:'From a meteor that almost made it.',                     fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:272, tier:'RARE', name:'Glass Flame',          icon:'🔥', desc:'Perfectly preserved combustion.',                        fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:273, tier:'RARE', name:'Bone Compass',         icon:'🦴', desc:'Points toward the nearest dead thing.',                  fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:274, tier:'RARE', name:'Iron Cloud',           icon:'☁️', desc:'Heavy with stored rain.',                                fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:275, tier:'RARE', name:'Cerulean Core',        icon:'🔵', desc:'The heart of a sapphire ocean.',                         fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:276, tier:'RARE', name:'Dream Crystal',        icon:'💎', desc:'Contains last night\'s best dream.',                     fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:277, tier:'RARE', name:'Brine Glass',          icon:'🧊', desc:'Sea glass shaped by 1000 years.',                        fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:278, tier:'RARE', name:'Vein of Light',        icon:'💡', desc:'A mineral that stores sunlight.',                        fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:279, tier:'RARE', name:'Fissure Stone',        icon:'🪨', desc:'Cracked open to reveal a tiny universe.',               fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:280, tier:'RARE', name:'Aqua Sigil',           icon:'🌊', desc:'Drawn in water, held by will.',                          fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:281, tier:'RARE', name:'Comet Shard',          icon:'☄️', desc:'Still warm from atmospheric entry.',                     fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:282, tier:'RARE', name:'Night Bloom',          icon:'🌑', desc:'A flower that photosynthesizes darkness.',               fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:283, tier:'RARE', name:'Abyssal Pearl',        icon:'🔘', desc:'From a depth no light has touched.',                     fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:284, tier:'RARE', name:'Crimson Circuit',      icon:'❤️', desc:'Technology and biology merged.',                         fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:285, tier:'RARE', name:'Astral Hook',          icon:'🪝', desc:'Snags things from other planes.',                        fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:286, tier:'RARE', name:'Copper Storm',         icon:'⚡', desc:'Orange lightning, contained.',                           fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:287, tier:'RARE', name:'Frost Spider',         icon:'🕷️', desc:'Made entirely of ice. Moves.',                           fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:288, tier:'RARE', name:'Hollow Prism',         icon:'🔷', desc:'Light enters. Something else exits.',                    fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:289, tier:'RARE', name:'Plasma Droplet',       icon:'🌕', desc:'The fourth state of matter, bottled.',                   fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:290, tier:'RARE', name:'Solstice Key',         icon:'🗝️', desc:'Works for 12 seconds per year.',                         fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:291, tier:'RARE', name:'Void Feather',         icon:'🪶', desc:'Heavy with nothing.',                                    fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:292, tier:'RARE', name:'Tideborn Knife',       icon:'🔪', desc:'The ocean gave birth to this blade.',                    fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:293, tier:'RARE', name:'Frozen Heartbeat',     icon:'❄️', desc:'A cardiac moment, stopped in time.',                    fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:294, tier:'RARE', name:'Resonance Core',       icon:'🔊', desc:'Vibrates with the frequency of reality.',               fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:295, tier:'RARE', name:'Ether Knot',           icon:'🪢', desc:'A knot tied in pure air.',                               fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:296, tier:'RARE', name:'Azure Ember',          icon:'🔵', desc:'Cold fire. Burns with sadness.',                         fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:297, tier:'RARE', name:'Deep Mirror',          icon:'🪞', desc:'Reflects what you\'re afraid of. Correctly.',            fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:298, tier:'RARE', name:'Solar Dust',           icon:'☀️', desc:'Ground from a solar flare.',                             fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:299, tier:'RARE', name:'Crystallized Wish',    icon:'💫', desc:'Someone wished hard enough.',                            fx:'shatter', shake:SHAKE.medium, cutscene:false },
{ id:300, tier:'RARE', name:'Veil Shard',           icon:'🌫️', desc:'A piece of the barrier between worlds.',                 fx:'shatter', shake:SHAKE.medium, cutscene:false },

// ─────────────────────────── EPIC (301–380) ───────────────────────────
{ id:301, tier:'EPIC', name:'Violet Nova',          icon:'💜', desc:'A supernova compressed into a gem.',                     fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:302, tier:'EPIC', name:'Phantom Crown',        icon:'👑', desc:'Worn by a ruler no one remembers. Yet.',               fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:303, tier:'EPIC', name:'Soul Prism',           icon:'🔮', desc:'Refracts the soul into its true colors.',               fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:304, tier:'EPIC', name:'Wraith Blade',         icon:'⚔️', desc:'Can cut through fear itself.',                          fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:305, tier:'EPIC', name:'Cosmos Thread',        icon:'🌌', desc:'A filament from the edge of the universe.',             fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:306, tier:'EPIC', name:'Rift Eye',             icon:'👁️', desc:'Sees across parallel realities.',                       fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:307, tier:'EPIC', name:'Moonshard Gauntlet',   icon:'🥊', desc:'Forged from 100 moonshards, night by night.',           fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:308, tier:'EPIC', name:'Time Splinter',        icon:'⏳', desc:'A needle-thin fragment of frozen time.',                fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:309, tier:'EPIC', name:'Storm Heart',          icon:'⛈️', desc:'Still beating. Thunderous.',                            fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:310, tier:'EPIC', name:'Astral Dagger',        icon:'🗡️', desc:'Phases through armor. Finds the real target.',          fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:311, tier:'EPIC', name:'Violet Flame',         icon:'🔥', desc:'Burns the past.',                                       fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:312, tier:'EPIC', name:'Infinity Loop',        icon:'♾️', desc:'Has no beginning or end. Neither do you.',              fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:313, tier:'EPIC', name:'Dark Sun',             icon:'🌑', desc:'A sun that gave up shining.',                           fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:314, tier:'EPIC', name:'Nexus Core',           icon:'💠', desc:'The crossroads of all energy.',                         fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:315, tier:'EPIC', name:'Dragon\'s Vow',        icon:'🐉', desc:'A promise the dragon made to the mountain.',            fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:316, tier:'EPIC', name:'Prismatic Armor',      icon:'🛡️', desc:'Absorbs and refracts all attacks.',                     fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:317, tier:'EPIC', name:'Void Lantern',         icon:'🏮', desc:'Lights the dark between the stars.',                    fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:318, tier:'EPIC', name:'Psyche Stone',         icon:'🧠', desc:'A stone with consciousness.',                           fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:319, tier:'EPIC', name:'Soulfire Orb',         icon:'🔴', desc:'Burns eternal. Fed by belief.',                         fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:320, tier:'EPIC', name:'Spectral Tome',        icon:'📚', desc:'Writes itself. You read what you need.',                fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:321, tier:'EPIC', name:'Temporal Anchor',      icon:'⚓', desc:'Keeps you from drifting through time.',                 fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:322, tier:'EPIC', name:'Phantom Rune',         icon:'🪬', desc:'Can\'t be seen. Can always be felt.',                   fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:323, tier:'EPIC', name:'Crimson Comet',        icon:'☄️', desc:'Blazes, leaves a trail, never stops.',                  fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:324, tier:'EPIC', name:'Soul Map',             icon:'🗺️', desc:'Shows the path to your true purpose.',                  fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:325, tier:'EPIC', name:'Aether Crown',         icon:'👑', desc:'Exists in all dimensions simultaneously.',              fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:326, tier:'EPIC', name:'Eclipse Heart',        icon:'💜', desc:'Beats with the rhythm of orbital mechanics.',           fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:327, tier:'EPIC', name:'Void Gauntlet',        icon:'🥊', desc:'Punches through the fabric of space.',                  fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:328, tier:'EPIC', name:'Resonance Ring',       icon:'💍', desc:'Amplifies every intention.',                            fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:329, tier:'EPIC', name:'Prism Storm',          icon:'🌀', desc:'A vortex of pure refracted light.',                     fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:330, tier:'EPIC', name:'Nether Seed',          icon:'🌱', desc:'Grows in the space between thoughts.',                  fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:331, tier:'EPIC', name:'Dimensional Chip',     icon:'💎', desc:'A crack in reality, shaped like a gem.',                fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:332, tier:'EPIC', name:'Ultraviolet Staff',    icon:'🪄', desc:'Channels frequencies invisible to most.',              fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:333, tier:'EPIC', name:'Gravity Lens',         icon:'🔭', desc:'Bends space like glasses bend light.',                  fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:334, tier:'EPIC', name:'Twilight Sword',       icon:'⚔️', desc:'Powered at the exact moment between day and night.',   fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:335, tier:'EPIC', name:'Soul Compass',         icon:'🧭', desc:'Points to what you were before you forgot.',            fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:336, tier:'EPIC', name:'Abyssal Relic',        icon:'🪨', desc:'Older than light.',                                     fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:337, tier:'EPIC', name:'Nebula Gauntlet',      icon:'🥊', desc:'Holds a galaxy in each fist.',                          fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:338, tier:'EPIC', name:'Rift Orb',             icon:'🔮', desc:'A portal, safely contained.',                           fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:339, tier:'EPIC', name:'Phantom Ship',         icon:'🚢', desc:'Travels seas that have no water.',                      fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:340, tier:'EPIC', name:'Star Cradle',          icon:'⭐', desc:'Where new stars are held until ready.',                 fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:341, tier:'EPIC', name:'Chrono Blade',         icon:'🗡️', desc:'Cuts forward and backward through time.',              fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:342, tier:'EPIC', name:'Living Rune',          icon:'🪬', desc:'It moves. It adapts. It evolves.',                      fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:343, tier:'EPIC', name:'Magma Crown',          icon:'👑', desc:'Liquid rock, never cooling.',                           fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:344, tier:'EPIC', name:'Stellar Core',         icon:'💫', desc:'The absolute center of a star.',                        fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:345, tier:'EPIC', name:'Warp Anchor',          icon:'⚓', desc:'Holds you steady as reality folds.',                    fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:346, tier:'EPIC', name:'Plasma Whip',          icon:'⚡', desc:'Cracks with the force of a solar eruption.',            fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:347, tier:'EPIC', name:'Obsidian Wings',       icon:'🦅', desc:'Each feather: volcanic glass.',                         fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:348, tier:'EPIC', name:'Psychic Mirror',       icon:'🪞', desc:'Shows others what you\'re thinking.',                   fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:349, tier:'EPIC', name:'Violet Serpent',       icon:'🐍', desc:'It knows what you\'re afraid of.',                      fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:350, tier:'EPIC', name:'Singularity Marble',   icon:'⚫', desc:'Pulls in light. Never lets go.',                        fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:351, tier:'EPIC', name:'Deep Rift Stone',      icon:'💠', desc:'Fell from a crack between dimensions.',                 fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:352, tier:'EPIC', name:'Phantom Tome',         icon:'📖', desc:'Pages turn. Nothing written. You understand it.',       fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:353, tier:'EPIC', name:'Nova Crystal',         icon:'💎', desc:'The crystallized moment of a star\'s death.',           fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:354, tier:'EPIC', name:'Ghost Forge',          icon:'🔨', desc:'Hammers without noise, shapes without heat.',           fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:355, tier:'EPIC', name:'Twin Star Ring',       icon:'💍', desc:'Two stars, orbiting your finger.',                      fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:356, tier:'EPIC', name:'Hollow Throne',        icon:'🪑', desc:'Whoever sits earns the realm\'s weight.',               fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:357, tier:'EPIC', name:'Shard of Will',        icon:'⚡', desc:'Pure determination, crystallized.',                     fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:358, tier:'EPIC', name:'Celestial Hook',       icon:'🪝', desc:'Catches falling stars.',                               fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:359, tier:'EPIC', name:'Tide Dragon Scale',    icon:'🐉', desc:'Shed by a dragon that swam the deep.',                  fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:360, tier:'EPIC', name:'Warped Mirror',        icon:'🪞', desc:'Bend it slightly: see tomorrow.',                       fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:361, tier:'EPIC', name:'Aurora Core',          icon:'🌈', desc:'The beating heart of northern lights.',                 fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:362, tier:'EPIC', name:'Fractured Legend',     icon:'📜', desc:'A myth that broke apart. This is a piece.',             fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:363, tier:'EPIC', name:'Entropy Shard',        icon:'💎', desc:'Slowly unmakes things it touches.',                     fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:364, tier:'EPIC', name:'Ancient Eye',          icon:'👁️', desc:'From a creature that saw everything.',                  fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:365, tier:'EPIC', name:'Gravity Well Gem',     icon:'🔮', desc:'Pulls nearby dice. Ensures higher rolls.',              fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:366, tier:'EPIC', name:'Phase Dagger',         icon:'🗡️', desc:'Exists between moments.',                               fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:367, tier:'EPIC', name:'Infinite Ember',       icon:'🔥', desc:'Fed by nothing. Burns forever.',                        fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:368, tier:'EPIC', name:'Stellar Map',          icon:'🗺️', desc:'Shows every star\'s destiny.',                          fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:369, tier:'EPIC', name:'Umbra Crown',          icon:'👑', desc:'Cast in the shadow of a dying star.',                   fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:370, tier:'EPIC', name:'Abyssal Bloom',        icon:'🌺', desc:'Beauty from the darkest depths.',                       fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:371, tier:'EPIC', name:'Void Chalice',         icon:'🏆', desc:'Holds a drink that never empties.',                     fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:372, tier:'EPIC', name:'Phantom Harp',         icon:'🎵', desc:'Plays the song of your life.',                          fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:373, tier:'EPIC', name:'Sunder Stone',         icon:'💎', desc:'Breaks anything, including barriers.',                  fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:374, tier:'EPIC', name:'Stellar Seed',         icon:'⭐', desc:'Grow it into a solar system.',                          fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:375, tier:'EPIC', name:'Glitch Fragment',      icon:'📱', desc:'Reality\'s error, held physical.',                      fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:376, tier:'EPIC', name:'Arcane Spire',         icon:'🏛️', desc:'A tower compressed to holding size.',                   fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:377, tier:'EPIC', name:'Rift Whale Bone',      icon:'🦴', desc:'From a whale that swims between worlds.',               fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:378, tier:'EPIC', name:'Hollow Storm',         icon:'🌀', desc:'A hurricane that forgot to blow.',                      fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:379, tier:'EPIC', name:'Entropy Orb',          icon:'🔮', desc:'Slowly turning everything to its base state.',          fx:'nova', shake:SHAKE.large, cutscene:false },
{ id:380, tier:'EPIC', name:'Mirror Galaxy',        icon:'🌌', desc:'A galaxy mirroring yours, reversed.',                   fx:'nova', shake:SHAKE.large, cutscene:false },

// ─────────────────────────── LEGENDARY (381–430) ───────────────────────────
{ id:381, tier:'LEGENDARY', name:'Solar Throne',         icon:'☀️', desc:'Sit and the system orbits you.',                        fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:382, tier:'LEGENDARY', name:'Dragon\'s Eye',        icon:'🐉', desc:'The last eye of the last dragon.',                      fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:383, tier:'LEGENDARY', name:'Gold Phoenix',         icon:'🦅', desc:'Rises, eternally, from golden ash.',                    fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:384, tier:'LEGENDARY', name:'Infinity Blade',       icon:'⚔️', desc:'Cannot be broken. Has never been tested.',              fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:385, tier:'LEGENDARY', name:'Celestial Engine',     icon:'⚙️', desc:'Powers the heavens.',                                   fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:386, tier:'LEGENDARY', name:'Crown of Ages',        icon:'👑', desc:'Every king who wore it is still inside.',               fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:387, tier:'LEGENDARY', name:'Titan\'s Hammer',      icon:'🔨', desc:'Shaped the mountains.',                                 fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:388, tier:'LEGENDARY', name:'Star Forge',           icon:'🌟', desc:'Still creating stars.',                                 fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:389, tier:'LEGENDARY', name:'World Seed',           icon:'🌍', desc:'Contains a world, waiting to unfold.',                  fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:390, tier:'LEGENDARY', name:'Eternal Flame',        icon:'🔥', desc:'Burns since before time was counted.',                  fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:391, tier:'LEGENDARY', name:'Void Throne',          icon:'🪑', desc:'Seat of authority over nothing.',                       fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:392, tier:'LEGENDARY', name:'Genesis Stone',        icon:'💎', desc:'The first gem ever formed.',                            fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:393, tier:'LEGENDARY', name:'Sky Leviathan Scale',  icon:'🐉', desc:'From a creature longer than continents.',               fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:394, tier:'LEGENDARY', name:'Time Crystal',         icon:'⏳', desc:'All moments exist here at once.',                       fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:395, tier:'LEGENDARY', name:'Primordial Rune',      icon:'🪬', desc:'The oldest written symbol.',                            fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:396, tier:'LEGENDARY', name:'Sunken God\'s Tear',   icon:'💧', desc:'The grief of a sleeping deity.',                        fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:397, tier:'LEGENDARY', name:'Supernova Fragment',   icon:'💥', desc:'From a star\'s last breath.',                           fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:398, tier:'LEGENDARY', name:'Omega Compass',        icon:'🧭', desc:'Points to the end of all things.',                      fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:399, tier:'LEGENDARY', name:'Absolute Mirror',      icon:'🪞', desc:'Shows objective truth.',                                fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:400, tier:'LEGENDARY', name:'Sacred Hourglass',     icon:'⏳', desc:'Flip it: time reverses.',                               fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:401, tier:'LEGENDARY', name:'World Tree Fragment',  icon:'🌲', desc:'A branch from the tree that holds all realms.',         fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:402, tier:'LEGENDARY', name:'Comet Heart',          icon:'☄️', desc:'What powers a comet\'s endless travel.',                fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:403, tier:'LEGENDARY', name:'Divine Anvil',         icon:'⚒️', desc:'Used to forge the first weapons.',                      fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:404, tier:'LEGENDARY', name:'Soul Ocean',           icon:'🌊', desc:'Contains the souls of the sea.',                        fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:405, tier:'LEGENDARY', name:'Ancient Algorithm',    icon:'📊', desc:'The original code of the universe.',                    fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:406, tier:'LEGENDARY', name:'Titan Crown',          icon:'👑', desc:'Too heavy for mortals.',                                fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:407, tier:'LEGENDARY', name:'Grand Orrery',         icon:'🪐', desc:'A model of reality that IS reality.',                   fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:408, tier:'LEGENDARY', name:'Fallen God\'s Ring',   icon:'💍', desc:'Still warm with divine power.',                         fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:409, tier:'LEGENDARY', name:'Absolute Zero Shard',  icon:'🧊', desc:'The coldest thing that can exist.',                     fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:410, tier:'LEGENDARY', name:'Core of a Star',       icon:'⭐', desc:'Gravity waves outward from your hand.',                 fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:411, tier:'LEGENDARY', name:'Final Memory',         icon:'🧠', desc:'The last thought before the void.',                     fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:412, tier:'LEGENDARY', name:'Primordial Sea',       icon:'🌊', desc:'The original ocean, in a bottle.',                      fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:413, tier:'LEGENDARY', name:'God\'s Compass',       icon:'🧭', desc:'Points to where it all begins.',                        fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:414, tier:'LEGENDARY', name:'Alpha Flame',          icon:'🔥', desc:'The first fire ever lit.',                              fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:415, tier:'LEGENDARY', name:'Celestial Armor',      icon:'🛡️', desc:'Forged from a star\'s corona.',                         fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:416, tier:'LEGENDARY', name:'Omega Blade',          icon:'⚔️', desc:'The last sword.',                                       fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:417, tier:'LEGENDARY', name:'Sacred Vein',          icon:'💛', desc:'A vein of gold from the earth\'s heart.',               fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:418, tier:'LEGENDARY', name:'The One Ring',         icon:'💍', desc:'They said there was only one.',                         fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:419, tier:'LEGENDARY', name:'Timeless Lantern',     icon:'🏮', desc:'Illuminates all eras at once.',                         fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:420, tier:'LEGENDARY', name:'Dragon God Fang',      icon:'🐉', desc:'From the oldest dragon. The first.',                   fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:421, tier:'LEGENDARY', name:'Universal Key',        icon:'🗝️', desc:'Opens any door in any world.',                          fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:422, tier:'LEGENDARY', name:'Source Crystal',       icon:'💎', desc:'Where all magic originates.',                           fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:423, tier:'LEGENDARY', name:'Endless Storm',        icon:'⛈️', desc:'A storm that never stops. Anywhere.',                   fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:424, tier:'LEGENDARY', name:'Titan\'s Heart',       icon:'❤️', desc:'Still beats. You can feel it from here.',               fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:425, tier:'LEGENDARY', name:'The Meridian',         icon:'🌐', desc:'The axis of the world.',                                fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:426, tier:'LEGENDARY', name:'Arcane Sun',           icon:'☀️', desc:'A sun that fuels magic instead of life.',               fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:427, tier:'LEGENDARY', name:'Ouroboros Scale',      icon:'🐍', desc:'From the serpent eating its own tail.',                 fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:428, tier:'LEGENDARY', name:'Void Star',            icon:'⭐', desc:'A star that emits darkness.',                           fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:429, tier:'LEGENDARY', name:'Heaven\'s Hammer',     icon:'🔨', desc:'Fell from above. Left a crater.',                       fx:'eclipse', shake:SHAKE.massive, cutscene:true  },
{ id:430, tier:'LEGENDARY', name:'The Grand Seal',       icon:'🔏', desc:'Holds something very, very large in check.',            fx:'eclipse', shake:SHAKE.massive, cutscene:true  },

// ─────────────────────────── MYTHIC (431–460) ───────────────────────────
{ id:431, tier:'MYTHIC', name:'Blood Moon',              icon:'🌕', desc:'The sky bled. This remained.',                          fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:432, tier:'MYTHIC', name:'Rift Dragon',             icon:'🐉', desc:'A dragon made of dimensional tears.',                   fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:433, tier:'MYTHIC', name:'Death Star Shard',        icon:'💀', desc:'From a star\'s violent end.',                           fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:434, tier:'MYTHIC', name:'Eternal Darkness',        icon:'🌑', desc:'Before the first light, this existed.',                 fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:435, tier:'MYTHIC', name:'God\'s Heartbeat',        icon:'❤️', desc:'Found: one heartbeat, from above.',                     fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:436, tier:'MYTHIC', name:'Chaos Engine',            icon:'⚙️', desc:'Drives entropy at maximum efficiency.',                 fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:437, tier:'MYTHIC', name:'Omega Phoenix',           icon:'🦅', desc:'The final rebirth of the ultimate bird.',               fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:438, tier:'MYTHIC', name:'Universe Thread',         icon:'🧵', desc:'A stitch holding existence together.',                  fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:439, tier:'MYTHIC', name:'Primordial Void',         icon:'⚫', desc:'The absence before creation.',                         fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:440, tier:'MYTHIC', name:'Absolute Rune',           icon:'🪬', desc:'Rewrites any law of physics.',                         fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:441, tier:'MYTHIC', name:'Eye of Oblivion',         icon:'👁️', desc:'Sees the end of everything.',                          fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:442, tier:'MYTHIC', name:'Creation Hammer',         icon:'🔨', desc:'Made everything. Used once.',                          fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:443, tier:'MYTHIC', name:'Titan\'s Throne',         icon:'🪑', desc:'Still warm.',                                          fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:444, tier:'MYTHIC', name:'Universal Compass',       icon:'🧭', desc:'Points to the origin of all things.',                   fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:445, tier:'MYTHIC', name:'Armageddon Blade',        icon:'⚔️', desc:'Forged for the end. Still waiting.',                    fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:446, tier:'MYTHIC', name:'God\'s Eye',              icon:'👁️', desc:'What they used to watch it all.',                       fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:447, tier:'MYTHIC', name:'Heaven\'s Tear',          icon:'💧', desc:'Fell when the first soul was made.',                    fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:448, tier:'MYTHIC', name:'The First Word',          icon:'📜', desc:'Whatever was said to begin everything.',                fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:449, tier:'MYTHIC', name:'Infinite Dragon',         icon:'🐉', desc:'A dragon with no end and no beginning.',               fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:450, tier:'MYTHIC', name:'Quantum God',             icon:'🌌', desc:'Exists in all states simultaneously.',                  fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:451, tier:'MYTHIC', name:'Broken Cosmos',          icon:'💥', desc:'Reality fractured. You hold a piece.',                  fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:452, tier:'MYTHIC', name:'Dark Matter Core',        icon:'⚫', desc:'The substance of invisible mass.',                      fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:453, tier:'MYTHIC', name:'Omega Storm',             icon:'⛈️', desc:'The last storm. The worst one.',                        fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:454, tier:'MYTHIC', name:'Soul of the Sun',         icon:'☀️', desc:'Extracted with enormous effort.',                       fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:455, tier:'MYTHIC', name:'Death Comet',             icon:'☄️', desc:'Extinction, crystallized.',                             fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:456, tier:'MYTHIC', name:'Silent God',              icon:'🤐', desc:'Whatever it said, it will not say again.',              fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:457, tier:'MYTHIC', name:'Vortex Core',             icon:'🌀', desc:'The center of a black hole, held harmless.',            fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:458, tier:'MYTHIC', name:'Primordial Shard',        icon:'💎', desc:'From before the universe had rules.',                   fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:459, tier:'MYTHIC', name:'Eternal Void Heart',      icon:'🌑', desc:'The heart of the nothing between stars.',               fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },
{ id:460, tier:'MYTHIC', name:'God Machine',             icon:'⚙️', desc:'Self-assembles. Runs on belief.',                       fx:'eclipse', shake:SHAKE.apocalyptic, cutscene:true },

// ─────────────────────────── DIVINE (461–480) ───────────────────────────
{ id:461, tier:'DIVINE', name:'Tear of Heaven',          icon:'✨', desc:'The sky wept. This formed.',                            fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:462, tier:'DIVINE', name:'Celestial Throne',        icon:'🪑', desc:'Where the highest sits.',                               fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:463, tier:'DIVINE', name:'God Shard',               icon:'💎', desc:'A fragment of the divine.',                             fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:464, tier:'DIVINE', name:'Soul of Creation',        icon:'🌟', desc:'What made the first thing.',                            fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:465, tier:'DIVINE', name:'Heaven\'s Core',          icon:'☁️', desc:'The essential center of paradise.',                     fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:466, tier:'DIVINE', name:'Divine Flame',            icon:'🔥', desc:'Burns only sins.',                                      fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:467, tier:'DIVINE', name:'Fate\'s Needle',          icon:'🪡', desc:'Stitches destinies together.',                          fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:468, tier:'DIVINE', name:'Celestial Map',           icon:'🗺️', desc:'Every soul, plotted.',                                  fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:469, tier:'DIVINE', name:'Heaven\'s Key',           icon:'🗝️', desc:'Opens the door everyone seeks.',                        fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:470, tier:'DIVINE', name:'Light Before Light',      icon:'🌟', desc:'Existed before the first photon.',                      fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:471, tier:'DIVINE', name:'The Source',              icon:'🌊', desc:'Where everything flows from.',                          fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:472, tier:'DIVINE', name:'Genesis Crystal',         icon:'💎', desc:'The first crystal. The blueprint.',                     fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:473, tier:'DIVINE', name:'Angel Feather',           icon:'🪶', desc:'From a wing that guards everything.',                   fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:474, tier:'DIVINE', name:'Sacred Flame Orb',        icon:'🔮', desc:'The orb of righteous fire.',                            fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:475, tier:'DIVINE', name:'Heaven\'s Hourglass',     icon:'⏳', desc:'Time flows upward inside.',                             fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:476, tier:'DIVINE', name:'The Highest Rune',        icon:'🪬', desc:'Above all others.',                                     fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:477, tier:'DIVINE', name:'Absolute Truth',          icon:'📜', desc:'One sentence. Changes everything.',                     fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:478, tier:'DIVINE', name:'Apex Throne',             icon:'🪑', desc:'Highest seat in all existence.',                        fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:479, tier:'DIVINE', name:'Infinite Crown',          icon:'👑', desc:'Crowns the ruler of all realms.',                       fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:480, tier:'DIVINE', name:'Godblood Diamond',        icon:'💎', desc:'Divine ichor, crystallized.',                           fx:'ascend', shake:SHAKE.apocalyptic, cutscene:true },

// ─────────────────────────── COSMIC (481–494) ───────────────────────────
{ id:481, tier:'COSMIC', name:'The Big Bang',            icon:'💥', desc:'The original moment.',                                  fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:482, tier:'COSMIC', name:'Multiverse Core',         icon:'🌌', desc:'Connects every universe.',                              fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:483, tier:'COSMIC', name:'Dimension Zero',          icon:'⚫', desc:'Before dimensions were a thing.',                       fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:484, tier:'COSMIC', name:'Reality\'s Edge',         icon:'🌀', desc:'Touch it: everything flickers.',                        fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:485, tier:'COSMIC', name:'The Architect\'s Tool',   icon:'🔧', desc:'Built reality. Left behind.',                           fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:486, tier:'COSMIC', name:'Cosmic Heartbeat',        icon:'❤️', desc:'The pulse under everything.',                           fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:487, tier:'COSMIC', name:'The Watcher\'s Eye',      icon:'👁️', desc:'Has seen it all. Knows.',                               fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:488, tier:'COSMIC', name:'Eternal Algorithm',       icon:'📊', desc:'The code behind the simulation.',                       fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:489, tier:'COSMIC', name:'Universal Memory',        icon:'🧠', desc:'Remembers everything that happened.',                   fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:490, tier:'COSMIC', name:'The Final Law',           icon:'📜', desc:'The rule above all others.',                            fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:491, tier:'COSMIC', name:'Beyond Infinity',         icon:'♾️', desc:'Larger than infinite. Smaller than you.',              fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:492, tier:'COSMIC', name:'The True Name',           icon:'🔤', desc:'Say it: everything responds.',                          fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:493, tier:'COSMIC', name:'Omega Flame',             icon:'🔥', desc:'The last fire. Burns until nothing remains.',           fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },
{ id:494, tier:'COSMIC', name:'The Absolute',            icon:'🌟', desc:'No description possible.',                              fx:'cosmos', shake:SHAKE.apocalyptic, cutscene:true },

// ─────────────────────────── TRANSCENDENT (495–499) ───────────────────────────
{ id:495, tier:'TRANSCENDENT', name:'The Unnamed Thing',    icon:'❓', desc:'It has no name because names don\'t contain it.',   fx:'transcend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:496, tier:'TRANSCENDENT', name:'Beyond Words',         icon:'✨', desc:'...',                                                fx:'transcend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:497, tier:'TRANSCENDENT', name:'The Paradox',          icon:'♾️', desc:'Exists by not existing.',                           fx:'transcend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:498, tier:'TRANSCENDENT', name:'Everything',           icon:'🌌', desc:'All at once.',                                       fx:'transcend', shake:SHAKE.apocalyptic, cutscene:true },
{ id:499, tier:'TRANSCENDENT', name:'Nothing',              icon:'⬛', desc:'And yet, here you are.',                             fx:'transcend', shake:SHAKE.apocalyptic, cutscene:true },

// ─────────────────────────── VOID (500) ───────────────────────────
{ id:500, tier:'VOID', name:'The Void Itself',          icon:'🕳️', desc:'You found it. It was always here. It is you.',          fx:'void_rift', shake:SHAKE.apocalyptic, cutscene:true, special:'void_ending' },
];

// Build weighted pool
function buildWeightedPool() {
  const pool = [];
  for (const r of RARITIES) {
    const tierData = TIERS[r.tier];
    const w = Math.round(tierData.weight);
    for (let i = 0; i < w; i++) pool.push(r.id);
  }
  return pool;
}

const WEIGHTED_POOL = buildWeightedPool();

function rollRarity() {
  const idx = Math.floor(Math.random() * WEIGHTED_POOL.length);
  const id  = WEIGHTED_POOL[idx];
  return RARITIES.find(r => r.id === id);
}

// Expose
window.RARITIES   = RARITIES;
window.TIERS      = TIERS;
window.FX         = FX;
window.SHAKE      = SHAKE;
window.rollRarity = rollRarity;
